#!/usr/bin/env bash
# AMS PreToolUse(*) hook — load prescriptive-rules.json and hard-block any tool
# call matching a deterministic regex/glob in the blocklist.
# Zero LLM. Sub-millisecond. Pairs with the tool-safety skill (which handles
# nuanced reasoning).
#
# prescriptive-rules.json is generated by learn-codebase (from approaches.md
# GUARD RAILS) or by the update skill. Schema:
# {
#   "version": 1,
#   "rules": [
#     {
#       "id": "theme-tokens-readonly",
#       "tools": ["Edit", "Write"],
#       "match": {"path_glob": "packages/ui/src/styles/theme-*.css"},
#       "action": "block",
#       "reason": "GUARD RAIL: theme-1.css is READ ONLY for all agents. Reserved for humans. See approaches.md §2."
#     }
#   ]
# }

set -e

CLAUDE_DIR="$CLAUDE_PROJECT_DIR/.claude"
RULES="$CLAUDE_DIR/prescriptive-rules.json"

if [ ! -f "$RULES" ]; then
  echo '{"continue": true, "suppressOutput": true}'
  exit 0
fi

INPUT=$(cat)

if ! command -v jq >/dev/null 2>&1; then
  # No jq → cannot evaluate JSON rules; pass through with a warning to the dev.
  echo '{"continue": true, "suppressOutput": false, "systemMessage": "prescriptive-rules-block: jq not installed; rules cannot be evaluated. Install jq to enable hard-block enforcement."}'
  exit 0
fi

TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // ""')
TOOL_INPUT=$(echo "$INPUT" | jq -c '.tool_input // {}')

# Iterate rules. For each rule that targets this tool, evaluate match.
BLOCK_REASON=""
RULE_ID=""

while IFS= read -r RULE; do
  RID=$(echo "$RULE" | jq -r '.id')
  TOOLS=$(echo "$RULE" | jq -r '.tools[]?' 2>/dev/null)
  ACTION=$(echo "$RULE" | jq -r '.action')

  # Check tool match (empty tools list = applies to all)
  TOOL_MATCH=false
  if [ -z "$TOOLS" ]; then
    TOOL_MATCH=true
  else
    while IFS= read -r T; do
      [ "$T" = "$TOOL_NAME" ] && TOOL_MATCH=true
    done <<< "$TOOLS"
  fi
  [ "$TOOL_MATCH" != "true" ] && continue

  # Evaluate match conditions
  PATH_GLOB=$(echo "$RULE" | jq -r '.match.path_glob // empty')
  CMD_REGEX=$(echo "$RULE" | jq -r '.match.command_regex // empty')

  HIT=false

  # path_glob: match against tool_input.file_path or tool_input.path
  if [ -n "$PATH_GLOB" ]; then
    P=$(echo "$TOOL_INPUT" | jq -r '.file_path // .path // empty')
    if [ -n "$P" ]; then
      # Convert glob to regex (simple: * → .*, ? → .)
      REGEX=$(echo "$PATH_GLOB" | sed 's/\./\\./g; s/\*/.*/g; s/?/./g')
      echo "$P" | grep -qE "^${REGEX}$" && HIT=true
    fi
  fi

  # command_regex: match against tool_input.command (Bash tool)
  if [ -n "$CMD_REGEX" ]; then
    C=$(echo "$TOOL_INPUT" | jq -r '.command // empty')
    if [ -n "$C" ]; then
      echo "$C" | grep -qE "$CMD_REGEX" && HIT=true
    fi
  fi

  if [ "$HIT" = "true" ] && [ "$ACTION" = "block" ]; then
    BLOCK_REASON=$(echo "$RULE" | jq -r '.reason')
    RULE_ID="$RID"
    break
  fi
done < <(jq -c '.rules[]' "$RULES")

if [ -n "$BLOCK_REASON" ]; then
  jq -n --arg id "$RULE_ID" --arg reason "$BLOCK_REASON" '{
    "continue": false,
    "suppressOutput": false,
    "stopReason": ("AMS prescriptive-rules block (rule \($id)): " + $reason)
  }'
  exit 0
fi

echo '{"continue": true, "suppressOutput": true}'
exit 0
