"""
Stub helpers for --stub-llm mode.

When the graph is invoked with '--stub-llm' in meta.flags, LLM nodes
return deterministic placeholder values so the full graph can be tested
end-to-end without making any Anthropic API calls.
"""

from __future__ import annotations

from state import (
    GraphState,
    StackSnapshotModel,
    BuildDeployModel,
    CognitiveTeamProposal,
)


def is_stub(state: GraphState) -> bool:
    return "--stub-llm" in state["meta"].get("flags", [])


def stub_stack() -> dict:
    return StackSnapshotModel(
        schema_version=1,
        runtime={"node": "stub"},
        package_manager={"name": "stub", "version": "0.0.0"},
        frameworks={"next": "stub"},
        testing={"runner": {}, "e2e": None},
        linting={},
        key_dependencies={},
        structure={"type": "stub", "orchestrator": None,
                   "apps": [], "packages": [], "platform": "stub",
                   "serialization": None},
    ).model_dump()


def stub_build_deploy() -> dict:
    return BuildDeployModel(
        solution_type="other",
        canonical_build="echo '[stub] build'",
        canonical_test="echo '[stub] test'",
        canonical_deploy="echo '[stub] deploy'",
    ).model_dump()


def stub_cognitive_team(target_basename: str) -> dict:
    prefix = (target_basename[:3] or "STB").upper()
    # Ensure 2-3 uppercase alpha chars
    prefix = "".join(c for c in prefix if c.isalpha())[:3].upper() or "STB"
    return CognitiveTeamProposal(
        cognitive_team=["synthesizer", "pragmatist"],
        primary_harness_for_single_mode="synthesizer",
        audit_primary_harness="skeptic",
        default_lenses=["security"],
        altitude_band_default="maker",
        synthesis_harness="synthesizer",
        work_item_prefix=prefix,
    ).model_dump()


STUB_PATTERNS_MD = """\
# Code Patterns

> **STUB** — generated by --stub-llm mode. Run without the flag for real analysis.

## No patterns detected in stub mode.
"""

STUB_APPROACHES_MD = """\
# Architectural Approaches

> **STUB** — generated by --stub-llm mode. Run without the flag for real analysis.

## No approaches detected in stub mode.
"""
