"""
domain_skills — Step 7: generate domain skill SKILL.md files.

canonicalize_skills() is deterministic Python. The per-skill LLM call
(DomainSkillBody) is skipped in stub mode; a placeholder SKILL.md is
written instead.
"""

from __future__ import annotations

import json
from pathlib import Path

from state import GraphState, DomainSkillEntry, has_fatal_error, add_warning, DomainSkillBody
from call_claude import structured
from config import SONNET, UMBRELLA_TABLE, MAX_DOMAIN_SKILLS
from stub_helpers import is_stub
from logger import step_start, step_end, artifact_write as log_artifact_write


def canonicalize_skills(sweep_files: list[str], stack: dict) -> list[str]:
    """
    Deterministic: map detected signals to canonical skill names.
    Uses UMBRELLA_TABLE priority order; caps at MAX_DOMAIN_SKILLS.
    """
    all_text = " ".join(sweep_files).lower()
    for v in stack.values():
        if isinstance(v, dict):
            all_text += " " + " ".join(v.keys()).lower()

    seen: set[str] = set()
    result: list[str] = []
    for signals, canonical_name in UMBRELLA_TABLE:
        if any(sig.lower() in all_text for sig in signals):
            if canonical_name not in seen:
                seen.add(canonical_name)
                result.append(canonical_name)
                if len(result) >= MAX_DOMAIN_SKILLS:
                    break
    return result


def _stub_skill_md(name: str) -> str:
    return (
        f"---\n"
        f"name: {name}\n"
        f"description: '[stub] {name} — run without --stub-llm for real content'\n"
        f"---\n\n"
        f"# {name}\n\n"
        f"> **STUB** — generated by --stub-llm mode.\n"
    )


def _real_skill_md(body: DomainSkillBody) -> str:
    lines = [
        "---",
        f"name: {body.name}",
        f"description: {body.frontmatter_description}",
        "---",
        "",
        f"# {body.name}",
        "",
        "## Project-specific Patterns",
        body.project_specific_patterns,
        "",
        "## Approaches & Guard Rails",
        body.project_specific_approaches,
        "",
    ]
    if body.cli_commands:
        lines += ["## CLI Commands", body.cli_commands, ""]
    if body.mcp_methods:
        lines += ["## MCP Methods", body.mcp_methods, ""]
    lines += [
        "## Documentation",
        f"- Official docs: {body.doc_fallback_url}",
        f"- Version in use: {body.doc_fallback_version}",
    ]
    return "\n".join(lines)


def run(state: GraphState) -> GraphState:
    if has_fatal_error(state):
        return state

    meta = state["meta"]
    target = Path(meta["target_path"])
    log = meta["log_file"]

    step_start(log, "7-domain_skills", "domain_skills")

    sweep = state.get("sweep")
    stack = state.get("stack") or {}
    files = sweep["files_read"] if sweep else []

    skill_names = canonicalize_skills(files, stack)
    if not skill_names:
        add_warning(state, "domain_skills: no canonical skills detected")
        step_end(log, "7-domain_skills", "domain_skills", "ok", "0 skills")
        return state

    entries: list[DomainSkillEntry] = []
    stub_mode = is_stub(state)

    patterns_md = state.get("patterns_md") or ""
    approaches_md = state.get("approaches_md") or ""
    build_deploy = json.dumps(state.get("build_deploy") or {}, indent=2)

    for name in skill_names:
        skills_dir = target / ".claude" / "skills" / name
        skills_dir.mkdir(parents=True, exist_ok=True)
        skill_path = skills_dir / "SKILL.md"

        if stub_mode:
            content = _stub_skill_md(name)
        else:
            system = (
                "You are writing a domain knowledge skill file for Claude Code. "
                "Extract only content relevant to this specific technology from the "
                "provided project context. Be precise and project-specific."
            )
            user = (
                f"Technology: {name}\n\n"
                f"patterns.md excerpt:\n{patterns_md[:4000]}\n\n"
                f"approaches.md excerpt:\n{approaches_md[:4000]}\n\n"
                f"build_deploy:\n{build_deploy}"
            )
            try:
                body = structured(
                    system_prompt=system,
                    user_message=user,
                    schema=DomainSkillBody,
                    model=SONNET,
                )
                content = _real_skill_md(body)
            except Exception as exc:
                add_warning(state, f"domain_skills: failed to generate {name}: {exc}")
                content = _stub_skill_md(name)

        skill_path.write_text(content, encoding="utf-8")
        log_artifact_write(log, f"skills/{name}/SKILL.md", str(skill_path),
                           size_bytes=len(content.encode("utf-8")))

        entries.append(DomainSkillEntry(
            name=name,
            file_path=str(skill_path),
            is_canonical=True,
            merged_from=[],
        ))

    state["domain_skills"] = entries
    step_end(log, "7-domain_skills", "domain_skills", "ok",
             f"{len(entries)} skills written")
    return state
